import { JSDOM } from "jsdom";

export type TrendKeyword={term:string;googleRank?:number;yahooRank?:number;sources:string[]};
export type TrendNewsArticle={id:string;source:string;title:string;description:string;url:string;imageUrl?:string;publishedAt:string;category:string;trendTerms:string[];googleRank?:number;yahooRank?:number;coverageCount:number;impactScore:number;importanceStars:1|2|3|4|5};
export type NewsTopic={id:string;title:string;summary:string;publishedAt:string;impactScore:number;importanceStars:1|2|3|4|5;trendBadges:string[];heat:number;articles:TrendNewsArticle[]};
const clean=(v:string)=>(v||"").replace(/\s+/g," ").replace(/[「」『』【】]/g,"").trim();
const norm=(v:string)=>clean(v).toLowerCase().replace(/[^ぁ-んァ-ヶ一-龠a-z0-9]+/gi,"");
const uniq=<T,>(a:T[])=>[...new Set(a)];
const dateOf=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString();};
async function getText(url:string,timeout=8000){const c=new AbortController();const timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)","Accept":"text/html,application/xml,text/xml,*/*","Accept-Language":"ja-JP,ja;q=0.9"}});if(!r.ok)throw new Error("HTTP "+r.status);return await r.text();}finally{clearTimeout(timer);}}
export async function fetchGoogleTrends():Promise<TrendKeyword[]>{try{const doc=new JSDOM(await getText("https://trends.google.com/trending/rss?geo=JP")).window.document;const out=uniq(Array.from(doc.querySelectorAll("item > title,entry > title")).map((e,i)=>({term:clean(e.textContent||""),googleRank:i+1})).filter(x=>x.term.length>=2)).slice(0,30);console.log("[TREND_PIPELINE] GOOGLE",JSON.stringify({count:out.length,top:out.slice(0,10)}));return out.map(x=>({term:x.term,googleRank:x.googleRank,sources:["Google Trends"]}));}catch(e){console.warn("[TREND_PIPELINE] GOOGLE_FAIL",e instanceof Error?e.message:String(e));return[];}}
export async function fetchYahooRealtimeTrends():Promise<TrendKeyword[]>{try{const doc=new JSDOM(await getText("https://search.yahoo.co.jp/realtime/")).window.document;const out:Array<{term:string;rank:number}>=[];for(const a of Array.from(doc.querySelectorAll("a[href]"))){const term=clean(a.textContent||"");const href=a.getAttribute("href")||"";if(term.length<2||term.length>60||!/realtime/i.test(href)||/検索|ログイン|一覧|画像|動画|ニュース|設定|ヘルプ|Yahoo!/i.test(term))continue;out.push({term,rank:out.length+1});}const map=new Map<string,{term:string;rank:number}>();for(const x of out){const k=norm(x.term);if(k&&!map.has(k))map.set(k,x);}const terms=[...map.values()].slice(0,30);console.log("[TREND_PIPELINE] YAHOO",JSON.stringify({count:terms.length,top:terms.slice(0,10)}));return terms.map(x=>({term:x.term,yahooRank:x.rank,sources:["Yahoo!リアルタイム検索"]}));}catch(e){console.warn("[TREND_PIPELINE] YAHOO_FAIL",e instanceof Error?e.message:String(e));return[];}}
function merge(a:TrendKeyword[],b:TrendKeyword[]){const m=new Map<string,TrendKeyword>();for(const x of a)m.set(norm(x.term),{...x});for(const x of b){const k=norm(x.term);if(!k)continue;const y=m.get(k);if(y){y.yahooRank=x.yahooRank;y.sources=uniq([...y.sources,"Yahoo!リアルタイム検索"]);}else m.set(k,{...x});}return[...m.values()].filter(x=>x.term).sort((x,y)=>Math.min(x.googleRank||99,x.yahooRank||99)-Math.min(y.googleRank||99,y.yahooRank||99));}
function category(t:string){if(/首相|総理|政府|国会|選挙|法案|外交|大統領|議会/.test(t))return"politics";if(/日銀|金利|物価|GDP|為替|円相場|景気|賃金/.test(t))return"economy";if(/株|日経平均|TOPIX|市場|債券/.test(t))return"market";if(/AI|半導体|IT|クラウド|サイバー|ソフトウェア/.test(t))return"technology";if(/事件|事故|地震|台風|火災|逮捕|死者|負傷/.test(t))return"society";return"other";}
async function newsQuery(key:string,q?:string){const p=new URLSearchParams({apikey:key,language:"ja",country:"jp",timeframe:"6"});if(q)p.set("q",q);const r=await fetch("https://newsdata.io/api/1/latest?"+p.toString(),{cache:"no-store",headers:{"Accept":"application/json"}});const d=await r.json();if(!r.ok||d?.status==="error")throw new Error(d?.results?.message||d?.message||"NewsData.io error");return Array.isArray(d?.results)?d.results:[];}
async function fetchNewsData(trends:TrendKeyword[]){const key=process.env.NEWSDATA_API_KEY;if(!key){console.warn("[TREND_PIPELINE] NEWSDATA_API_KEY missing");return[] as TrendNewsArticle[];}const qs=trends.slice(0,12);const batches=await Promise.allSettled([...qs.map(t=>newsQuery(key,t.term)),newsQuery(key)]);const raw=batches.flatMap(x=>x.status==="fulfilled"?x.value:[]);const seen=new Set<string>();const out:TrendNewsArticle[]=[];for(const x of raw){const url=String(x?.link||"");const title=clean(String(x?.title||""));if(!url||!title||seen.has(url)||!/^https?:\/\//i.test(url))continue;seen.add(url);const desc=clean(String(x?.description||""));const hit=trends.filter(t=>(title+" "+desc).toLowerCase().includes(t.term.toLowerCase())).slice(0,5);const g=Math.min(...hit.map(t=>t.googleRank||99),99),y=Math.min(...hit.map(t=>t.yahooRank||99),99),both=g<99&&y<99;const impact=Math.min(15,(both?9:g<99||y<99?5:1)+Math.min(4,hit.length)+Math.max(0,4-Math.floor(Math.min(g,y)/5)));out.push({id:"newsdata:"+String(x.article_id||url),source:clean(String(x.source_name||x.source_id||"NewsData.io")),title,description:desc,url,imageUrl:x.image_url?String(x.image_url):undefined,publishedAt:dateOf(String(x.pubDate||"")),category:category(title+" "+desc),trendTerms:hit.map(t=>t.term),googleRank:g<99?g:undefined,yahooRank:y<99?y:undefined,coverageCount:hit.length,impactScore:impact,importanceStars:impact>=13?5:impact>=9?4:impact>=5?3:impact>=2?2:1});}console.log("[TREND_PIPELINE] NEWSDATA",JSON.stringify({queries:qs.length,raw:raw.length,articles:out.length}));return out;}
function sim(a:string,b:string){const x=norm(a),y=norm(b);if(!x||!y)return 0;if(x.includes(y)||y.includes(x))return 1;const grams=(s:string)=>new Set(Array.from({length:Math.max(0,s.length-1)},(_,i)=>s.slice(i,i+2)));const ax=grams(x),by=grams(y);let n=0;for(const g of ax)if(by.has(g))n++;return n/Math.max(1,ax.size+by.size-n);}
function topicsOf(articles:TrendNewsArticle[]):NewsTopic[]{const topics:NewsTopic[]=[];for(const a of articles){const t=topics.find(t=>sim(t.title,a.title)>=0.38||a.trendTerms.some(k=>t.articles.some(x=>x.trendTerms.includes(k))));if(t)t.articles.push(a);else topics.push({id:"topic:"+a.id,title:a.title,summary:a.description,publishedAt:a.publishedAt,impactScore:a.impactScore,importanceStars:a.importanceStars,trendBadges:[],heat:0,articles:[a]});}for(const t of topics){const all=t.articles;const g=all.filter(a=>a.googleRank).sort((a,b)=>(a.googleRank||99)-(b.googleRank||99))[0];const y=all.filter(a=>a.yahooRank).sort((a,b)=>(a.yahooRank||99)-(b.yahooRank||99))[0];t.impactScore=Math.min(15,Math.max(...all.map(a=>a.impactScore))+Math.min(4,Math.floor((all.length-1)/2)));t.importanceStars=t.impactScore>=13?5:t.impactScore>=9?4:t.impactScore>=5?3:t.impactScore>=2?2:1;t.trendBadges=[];if(g?.googleRank===1)t.trendBadges.push("📈 Google検索急上昇");else if(g?.googleRank&&g.googleRank<=5)t.trendBadges.push("📈 Google検索上位");if(y?.yahooRank===1)t.trendBadges.push("🔥 Yahoo!トレンド1位");else if(y?.yahooRank&&y.yahooRank<=5)t.trendBadges.push("🔥 Yahoo!トレンド上位");if(all.length>=4)t.trendBadges.push("📰 報道多数");t.heat=Math.min(100,t.impactScore*6+Math.min(40,all.length*8));}return topics.sort((a,b)=>new Date(b.publishedAt).getTime()-new Date(a.publishedAt).getTime());}
export async function collectTrendNews(){const started=Date.now();const[google,yahoo]=await Promise.all([fetchGoogleTrends(),fetchYahooRealtimeTrends()]);const trends=merge(google,yahoo);const articles=await fetchNewsData(trends);const topics=topicsOf(articles);const heatByHour:Record<string,{count:number;heat:number}>={};for(const t of topics){const key=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hour12:false}).format(new Date(t.publishedAt));heatByHour[key]??={count:0,heat:0};heatByHour[key].count+=t.articles.length;heatByHour[key].heat+=t.heat;}console.log("[TREND_PIPELINE] SUMMARY",JSON.stringify({google:google.length,yahoo:yahoo.length,keywords:trends.length,articles:articles.length,topics:topics.length,durationMs:Date.now()-started}));return{google,yahoo,trends,articles,topics,heatByHour};}
