import { JSDOM } from "jsdom";

export type TrendKeyword={term:string;googleRank?:number;yahooRank?:number;sources:string[]};
export type TrendNewsArticle={id:string;source:string;title:string;description:string;url:string;imageUrl?:string;publishedAt:string;category:string;trendTerms:string[];googleRank?:number;yahooRank?:number;coverageCount:number;impactScore:number;importanceStars:1|2|3|4|5};
export type NewsTopic={id:string;title:string;summary:string;publishedAt:string;impactScore:number;importanceStars:1|2|3|4|5;trendBadges:string[];heat:number;articles:TrendNewsArticle[]};
const clean=(v:string)=>(v||"").replace(/\s+/g," ").replace(/[「」『』【】]/g,"").trim();
const norm=(v:string)=>clean(v).toLowerCase().replace(/[^ぁ-んァ-ヶ一-龠a-z0-9]+/gi,"");
const uniq=<T,>(a:T[])=>[...new Set(a)];
const dateOf=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString();};
async function getText(url:string,timeout=8000){const c=new AbortController();const timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)","Accept":"text/html,application/xml,text/xml,*/*","Accept-Language":"ja-JP,ja;q=0.9"}});if(!r.ok)throw new Error("HTTP "+r.status);return await r.text();}finally{clearTimeout(timer);}}
export async function fetchGoogleTrends():Promise<TrendKeyword[]>{try{const doc=new JSDOM(await getText("https://trends.google.com/trending/rss?geo=JP")).window.document;const out=uniq(Array.from(doc.querySelectorAll("item > title,entry > title")).map((e,i)=>({term:clean(e.textContent||""),googleRank:i+1})).filter(x=>x.term.length>=2)).slice(0,30);console.log("[TREND_PIPELINE] GOOGLE",JSON.stringify({count:out.length,top:out.slice(0,10)}));return out.map(x=>({term:x.term,googleRank:x.googleRank,sources:["Google Trends"]}));}catch(e){console.warn("[TREND_PIPELINE] GOOGLE_FAIL",e instanceof Error?e.message:String(e));return[];}}
function yahooTerm(raw:string){let s=clean(raw).replace(/^\d+\s*/,"").replace(/^[0-9]+位/,"").split(/急上昇|https?:\/\//i)[0].split(/[／/]/)[0].trim();const hash=s.match(/#([^\s#]+)/);if(hash)return clean(hash[1]).replace(/[！!、。,:：]+$/,"").slice(0,24);s=s.split(/(?:返信数|リポスト数|いいね数|こいつ|誰よりも|これは|なんだこれ|繰り返します|本日)/i)[0];s=s.split(/[！!。！？]/)[0];s=s.replace(/^[^\p{L}\p{N}ぁ-んァ-ヶ一-龠]+/u,"");return clean(s).slice(0,24);}
function isMeaningfulYahooTerm(term:string){const s=clean(term);if(s.length<2||s.length>24)return false;if(/[\u{1F300}-\u{1FAFF}]/u.test(s))return false;if(/(?:えっち|セックス|裸|ポルノ|アダルト|殺す|死ね)/i.test(s))return false;const letters=(s.match(/[ぁ-んァ-ヶ一-龠A-Za-z0-9]/g)||[]).length;return letters>=3;}
export async function fetchYahooRealtimeTrends():Promise<TrendKeyword[]>{try{const doc=new JSDOM(await getText("https://search.yahoo.co.jp/realtime/")).window.document;const out:Array<{term:string;rank:number}>=[];for(const a of Array.from(doc.querySelectorAll("a[href]"))){const raw=clean(a.textContent||"");const href=a.getAttribute("href")||"";if(!/realtime/i.test(href)||/検索|ログイン|一覧|画像|動画|ニュース|設定|ヘルプ|Yahoo!/i.test(raw))continue;const rankMatch=raw.match(/^(?:\s*)?(\d+)\s*(?:位)?/);if(!rankMatch)continue;const term=yahooTerm(raw.slice(rankMatch[0].length));if(term.length<2||term.length>40)continue;out.push({term,rank:Number(rankMatch[1])});}const map=new Map<string,{term:string;rank:number}>();for(const x of out){const k=norm(x.term);if(k&&!map.has(k))map.set(k,x);}const terms=[...map.values()].sort((a,b)=>a.rank-b.rank).slice(0,30);console.log("[TREND_PIPELINE] YAHOO",JSON.stringify({count:terms.length,top:terms.slice(0,10)}));return terms.map(x=>({term:x.term,yahooRank:x.rank,sources:["Yahoo!リアルタイム検索"]}));}catch(e){console.warn("[TREND_PIPELINE] YAHOO_FAIL",e instanceof Error?e.message:String(e));return[];}}
function merge(a:TrendKeyword[],b:TrendKeyword[]){const m=new Map<string,TrendKeyword>();for(const x of a)m.set(norm(x.term),{...x});for(const x of b){const k=norm(x.term);if(!k)continue;const y=m.get(k);if(y){y.yahooRank=x.yahooRank;y.sources=uniq([...y.sources,"Yahoo!リアルタイム検索"]);}else m.set(k,{...x});}return[...m.values()].filter(x=>x.term).sort((x,y)=>Math.min(x.googleRank||99,x.yahooRank||99)-Math.min(y.googleRank||99,y.yahooRank||99));}
function category(t:string){if(/首相|総理|政府|国会|選挙|法案|外交|大統領|議会/.test(t))return"politics";if(/日銀|金利|物価|GDP|為替|円相場|景気|賃金/.test(t))return"economy";if(/株|日経平均|TOPIX|市場|債券/.test(t))return"market";if(/AI|半導体|IT|クラウド|サイバー|ソフトウェア/.test(t))return"technology";if(/事件|事故|地震|台風|火災|逮捕|死者|負傷/.test(t))return"society";return"other";}
async function googleNewsQuery(q:string){const started=Date.now();const url="https://news.google.com/rss/search?"+new URLSearchParams({q,hl:"ja",gl:"JP",ceid:"JP:ja"}).toString();try{const xml=await getText(url,10000);const doc=new JSDOM(xml,{contentType:"text/xml"}).window.document;const items=Array.from(doc.querySelectorAll("item"));const results=items.map((item:any)=>{const title=clean(item.querySelector("title")?.textContent||"");const link=clean(item.querySelector("link")?.textContent||"");const description=clean(item.querySelector("description")?.textContent||"");const pubDate=clean(item.querySelector("pubDate")?.textContent||"");const source=clean(item.querySelector("source")?.textContent||"Google News");return{title,link,description,pubDate,source};}).filter(x=>x.title&&x.link&&(x.link.startsWith("http://")||x.link.startsWith("https://")));console.log("[TREND_PIPELINE] GOOGLE_NEWS_QUERY_OK",JSON.stringify({query:q,status:200,count:results.length,durationMs:Date.now()-started}));return results;}catch(e){console.warn("[TREND_PIPELINE] GOOGLE_NEWS_QUERY_FAIL",JSON.stringify({query:q,error:e instanceof Error?e.message:String(e),durationMs:Date.now()-started}));return[];}}
function newsSearchTerm(term:string){let s=clean(term).replace("急上昇","").trim();const hashIndex=s.indexOf("#");if(hashIndex>=0)s=s.slice(hashIndex+1).split(" ")[0];s=s.replace(/^\d+/,"").trim();return clean(s).slice(0,24);}

async function fetchNewsData(trends:TrendKeyword[]){
  const googleTerms=trends.filter(t=>t.googleRank&&t.googleRank<=10).map(t=>({...t,searchTerm:newsSearchTerm(t.term)})).filter(t=>t.searchTerm.length>=2);
  const yahooTerms=trends.filter(t=>t.yahooRank&&t.yahooRank<=10).map(t=>({...t,searchTerm:newsSearchTerm(t.term)})).filter(t=>t.searchTerm.length>=2&&isMeaningfulYahooTerm(t.searchTerm));
  const selectedMap=new Map<string,typeof googleTerms[number]>();
  for(const t of [...googleTerms,...yahooTerms]){const k=norm(t.searchTerm);const prev=selectedMap.get(k);if(!prev)selectedMap.set(k,t);else selectedMap.set(k,{...prev,googleRank:t.googleRank??prev.googleRank,yahooRank:t.yahooRank??prev.yahooRank,sources:uniq([...prev.sources,...t.sources])});}
  const selected=[...selectedMap.values()].sort((a,b)=>Math.min(a.googleRank??99,a.yahooRank??99)-Math.min(b.googleRank??99,b.yahooRank??99));
  console.log("[TREND_PIPELINE] GOOGLE_NEWS_START",JSON.stringify({googleTerms:googleTerms.map(t=>({term:t.searchTerm,rank:t.googleRank})),yahooTerms:yahooTerms.map(t=>({term:t.searchTerm,rank:t.yahooRank})),selectedTerms:selected.map(t=>t.searchTerm),queries:selected.length}));
  const batches=await Promise.all(selected.map(async t=>({term:t,articles:await googleNewsQuery(t.searchTerm.includes(" ") ? '"' + t.searchTerm + '"' : t.searchTerm)})));
  const raw=batches.flatMap(x=>x.articles.map(article=>({article,term:x.term})));
  console.log("[TREND_PIPELINE] GOOGLE_NEWS_BATCH_SUMMARY",JSON.stringify({requested:batches.length,succeeded:batches.length,raw:raw.length}));
  const seen=new Set<string>();const out:TrendNewsArticle[]=[];
  for(const item of raw){const x=item.article;const url=String(x.link||"");const title=clean(String(x.title||""));if(!url||!title||seen.has(url)||!(url.startsWith("http://")||url.startsWith("https://")))continue;const desc=clean(String(x.description||"")).replace(/<[^>]+>/g," ");const haystack=norm(title+" "+desc);const hit=selected.filter(t=>haystack.includes(norm(t.searchTerm))).slice(0,5);if(!hit.length)continue;seen.add(url);
    const googleHits=hit.filter(t=>t.googleRank);const yahooHits=hit.filter(t=>t.yahooRank);const g=googleHits.length?Math.min(...googleHits.map(t=>t.googleRank!)):99;const y=yahooHits.length?Math.min(...yahooHits.map(t=>t.yahooRank!)):99;const both=g<99&&y<99;
    const best=Math.min(g,y);const rankBonus=best<=1?4:best<=3?3:best<=5?2:best<=10?1:0;const impact=Math.min(15,(both?8:3)+rankBonus+Math.min(2,hit.length-1));
    const stars:1|2|3|4|5=both&&g<=3&&y<=3?5:both&&g<=5&&y<=5?4:(both||best<=3)?3:2;
    out.push({id:"googlenews:"+url,title,description:desc,url,source:clean(String(x.source||"Google News")),imageUrl:undefined,publishedAt:dateOf(String(x.pubDate||"")),category:category(title+" "+desc),trendTerms:hit.map(t=>t.term),googleRank:g<99?g:undefined,yahooRank:y<99?y:undefined,coverageCount:hit.length,impactScore:impact,importanceStars:stars});
  }
  console.log("[TREND_PIPELINE] GOOGLE_NEWS",JSON.stringify({queries:selected.length,raw:raw.length,articles:out.length,googleOnly:out.filter(a=>a.googleRank&&!a.yahooRank).length,yahooOnly:out.filter(a=>a.yahooRank&&!a.googleRank).length,both:out.filter(a=>a.googleRank&&a.yahooRank).length,top:out.slice(0,10).map(a=>({title:a.title,googleRank:a.googleRank,yahooRank:a.yahooRank,stars:a.importanceStars,terms:a.trendTerms}))}));return out;
}
function sim(a:string,b:string){const x=norm(a),y=norm(b);if(!x||!y)return 0;if(x.includes(y)||y.includes(x))return 1;const grams=(s:string)=>new Set(Array.from({length:Math.max(0,s.length-1)},(_,i)=>s.slice(i,i+2)));const ax=grams(x),by=grams(y);let n=0;for(const g of ax)if(by.has(g))n++;return n/Math.max(1,ax.size+by.size-n);}
function topicsOf(articles:TrendNewsArticle[]):NewsTopic[]{const topics:NewsTopic[]=[];for(const a of articles){const t=topics.find(t=>sim(t.title,a.title)>=0.38||a.trendTerms.some(k=>t.articles.some(x=>x.trendTerms.includes(k))));if(t)t.articles.push(a);else topics.push({id:"topic:"+a.id,title:a.title,summary:a.description,publishedAt:a.publishedAt,impactScore:a.impactScore,importanceStars:a.importanceStars,trendBadges:[],heat:0,articles:[a]});}for(const t of topics){const all=t.articles;const g=all.filter(a=>a.googleRank).sort((a,b)=>(a.googleRank||99)-(b.googleRank||99))[0];const y=all.filter(a=>a.yahooRank).sort((a,b)=>(a.yahooRank||99)-(b.yahooRank||99))[0];const relatedBonus=Math.min(3,Math.floor((all.length-1)/2));const baseImpact=Math.max(...all.map(a=>a.impactScore));t.impactScore=Math.min(15,baseImpact+relatedBonus);t.importanceStars=t.impactScore>=13?5:t.impactScore>=9?4:t.impactScore>=5?3:t.impactScore>=2?2:1;t.trendBadges=[];if(g?.googleRank&&g.googleRank<=5)t.trendBadges.push("google");if(y?.yahooRank&&y.yahooRank<=5)t.trendBadges.push("yahoo");const sourceCount=new Set(all.map(a=>a.source).filter(Boolean)).size;if(sourceCount>=3)t.trendBadges.push("coverage");t.heat=Math.min(100,t.impactScore*6+Math.min(40,all.length*8));}return topics.sort((a,b)=>new Date(b.publishedAt).getTime()-new Date(a.publishedAt).getTime());}
export async function collectTrendNews(){const started=Date.now();const[google,yahoo]=await Promise.all([fetchGoogleTrends(),fetchYahooRealtimeTrends()]);const trends=merge(google,yahoo);const articles=await fetchNewsData(trends);const topics=topicsOf(articles);const heatByHour:Record<string,{count:number;heat:number}>={};for(const t of topics){const key=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hour12:false}).format(new Date(t.publishedAt));heatByHour[key]??={count:0,heat:0};heatByHour[key].count+=t.articles.length;heatByHour[key].heat+=t.heat;}console.log("[TREND_PIPELINE] SUMMARY",JSON.stringify({google:google.length,yahoo:yahoo.length,keywords:trends.length,articles:articles.length,topics:topics.length,durationMs:Date.now()-started}));return{google,yahoo,trends,articles,topics,heatByHour};}
